name = "DeutschZ GroundZero";
picture = "";
logo = "";
logoSmall = "";
logoOver = "";
tooltip = "DeutschZ GroundZero";
overview = "DeutschZ GroundZero: staged PvE/PvP event with autogenerated fast-test config, zombies, fallback AI, marker/3D-marker requests, chat notifications and extraction flow.";
action = "";
author = "Patrick Sluzalek / fck1701";
<<<<<<< HEAD
version = "0.9.4-campaign-chain-test";
=======
version = "0.9.3-online-test";
>>>>>>> 39fa93c734f52a69c045816aa7b5632b5a10d772
